### ISSUE TITLE
Error appears in console when incorrect password was entered during login

### ISSUE THREAD

**Issue by darko-mijic** [meteor-space/donations#15]
This prints out in console on the server side when incorrect password was entered during login:

```Exception in onLoginFailure callback: Error: Match error: Expected plain object in field error
at check (packages/check/match.js:33:1)
at LoginFailed.Struct (packages/space_base/source/struct.coffee:10:5)
at LoginFailed.Space.Struct.extend.Constructor (source/serializables/event.js:17:25)
at LoginFailed.Event (eval at <anonymous> (packages/space_base/source/object.coffee:94:17), <anonymous>:2:38)
at LoginFailed.Constructor (packages/space_base/source/object.coffee:89:53)
at new LoginFailed (eval at <anonymous> (packages/space_base/source/object.coffee:94:17), <anonymous>:2:44)
at source/server/publishers/login-publisher.js:22:22
at runAndHandleExceptions (packages/callback-hook/hook.js:133:1)
at packages/callback-hook/hook.js:140:1
at accounts_server.js:172:5

```
```

**Comment by DominikGuzei** [comment]
Yep, that's a bug in `space:accounts` that i also noticed at some point. Thanks!
