### ISSUE TITLE
We have a failing domain logic test and domain logic was not modified

### ISSUE THREAD

**Issue by darko-mijic** [meteor-space/donations#54]
```
S: tinytest - Donations.OrgRegistration - registering an organization - signs up an admin and creates the organization : !!!!!!!!! FAIL !!!!!!!!!!!
Error: key Donations.OrgRegistrationId must not contain '.'
    at Object.Future.wait (/home/ubuntu/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:395:16)
    at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
    at [object Object].MongoConnection.(anonymous function) [as insert] (packages/mongo/mongo_driver.js:736:1)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/mongo/collection.js:590:1)
    at CommitStore.Space.eventSourcing.CommitStore.CommitStore.add (packages/space_event-sourcing/source/server/infrastructure/commit_store.coffee:57:27)
    at Repository.Space.eventSourcing.Repository.Repository.save (packages/space_event-sourcing/source/server/infrastructure/repository.coffee:29:18)
    at packages/space_event-sourcing/source/server/infrastructure/router.coffee:64:21
    at CommandBus.Space.messaging.CommandBus.CommandBus.send (packages/space_messaging/source/command_bus.coffee:25:7)
    at TestApp.Space.Application.mixin.send (packages/space_messaging/source/mixins/application-helpers.coffee:14:39)
    at AggregateTest._sendMessagesThroughApp (packages/space_testing/source/bdd/aggregates-bdd-api.coffee:77:15)
    - - - - -
    at Error (<anonymous>)
    at Function.checkKey (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:1474:13)
    at serializeObject (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:373:14)
    at packElement (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:881:23)
    at serializeObject (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:377:15)
    at packElement (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:881:23)
    at serializeObject (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:377:15)
    at packElement (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:881:23)
    at serializeObject (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:360:15)
    at packElement (/home/ubuntu/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:881:23)

```

**Comment by darko-mijic** [comment]
Locally this is not failing and it probably will after i update dependencies using `mgp`. This is probably related with latest changes to space:base. I will do the update to latest packages and start debugging.

**Comment by DominikGuzei** [comment]
Yep true, that's why we should stay away from using `branch: "develop`" with mgp. `develop` does not always guarantee to be backward compatible :wink: 

But the issue here is different i guess, it should be backward compatible but something broke. Will take a look at it

**Comment by rhyslbw** [comment]
> that's why we should stay away from using branch: "develop with mgp

No we just need to switch to a specific commit before merging, or before finalising the PR! That setting is dev-only

**Comment by rhyslbw** [comment]
FYI, Kadira has been catching this error, so it's a bug for sure as the app hasn't been redeployed since those library changes

**Comment by darko-mijic** [comment]
I am pegging in mgp configuration to commits for donations in `chore/add-auth-checks`branch. I will leave this issue to you @DominikGuzei. You can reproduce it by checking out develop branch of donations. 

This is happening after changes to serialization in core packages. And this is causing the problem in the app:
`eventCorrelationProperty: 'Donations.OrgRegistrationId',`

**Comment by DominikGuzei** [comment]
Ok, the problem is simple:
since we are now serializing into real mongodb structures we cannot use dots in our property keys anymore. This was possible before with EJSON.

Since we didn't pin down the mgp version to commit hashes, the install script on the server propably was re-run and installed the latest develop version.

@darko-mijic will put up a PR with the correct versions pinned
